version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: discord-notion-bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - RUN_IN_DOCKER=true
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - discord-notion-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  discord-notion-network:
    driver: bridge
